# Generated by Django 4.1.3 on 2022-11-22 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 22)),
        ),
    ]
